services:
  - type: web
    name: legendes-du-monde
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      FLASK_ENV: production
